services:
  frontend:
    build: ./frontend
    networks:
      - caddy_network
    labels:
      caddy: ${REPO_NAME}
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy_network:
    external: true